Legibilidad
===========

Spanish text readability calculations.

This script is made to test the readability of a given Spanish text. It calculates:

* Fernández Huerta's readability score
* Szigriszt-Pazos' perspicuity score
* Inflesz readability scale

How to use
==========

1. Download this files:
* `legibilidad.py <https://raw.githubusercontent.com/amunozf/legibilidad/master/legibilidad.py>`_
* `nal.py <https://raw.githubusercontent.com/amunozf/cifra-a-texto/master/nal.py>`_
* `separasilabas.py <https://raw.githubusercontent.com/amunozf/separasilabas/master/separasilabas.py>`_

2. Copy them to the same folder as legibilidad.py
3. See "ejemplo.py" to find out how it works.
